services:
  - type: web
    name: lakshmi-fh-frontend
    env: static
    buildCommand: cd "A Front End/lakshmi_FH" && npm install && npm run build
    staticPublishPath: A Front End/lakshmi_FH/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
